### ISSUE TITLE
Unable to instantiate fragment com.irozon.alertview.fragments.DialogFragment: could not find Fragment constructor

### ISSUE THREAD

**Issue by nowackipawel** [Hamadakram/AlertView#3]
When screen is rotating.

    java.lang.RuntimeException: Unable to start activity ComponentInfo{***.app.activities.ProfileActivity}: android.support.v4.app.Fragment$InstantiationException: Unable to instantiate fragment com.irozon.alertview.fragments.DialogFragment: could not find Fragment constructor
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4699)
        at android.app.ActivityThread.-wrap18(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1595)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: android.support.v4.app.Fragment$InstantiationException: Unable to instantiate fragment com.irozon.alertview.fragments.DialogFragment: could not find Fragment constructor
        at android.support.v4.app.Fragment.instantiate(Fragment.java:383)
        at android.support.v4.app.FragmentContainer.instantiate(FragmentContainer.java:33)
        at android.support.v4.app.FragmentState.instantiate(FragmentState.java:79)
        at android.support.v4.app.FragmentManagerImpl.restoreAllState(FragmentManager.java:3080)
        at android.support.v4.app.FragmentController.restoreAllState(FragmentController.java:152)
        at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:330)
        at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:84)

**Comment by Natoito** [comment]
The same here but on release. I checked all my fragments and I all of them has paramerless constructors
